baseURL = 'https://agentelement.net/'
languageCode = 'en-us'
title = "~/agentelement"
theme = 'hugo-theme-m10c'

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"

[[menu.main]]
  identifier = "hacks"
  name = "Hacks"
  url = "/hacks/"

[[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"

[[menu.main]]
  identifier = "pgp"
  name = "PGP"
  url = "/pgp/"

[params]
    avatar = "gal.jpg"
    author = "agentelement"
    description = "Sometimes serious. Mostly goofy."

[params.style]
  darkestColor = "#1B1C1E"
  darkColor = "#232326"
  lightColor = "#a7aab0"
  lightestColor = "#c7cad0"
  primaryColor = "#57A5E5"

[[params.social]]
  icon = "brand-github"
  name = "The Hub"
  url = "https://github.com/agentelement"

[[params.social]]
  icon = "brand-mastodon"
  name = "'stodon"
  url = "https://mathstodon.xyz/@agentelement"

[[params.social]]
  icon = "brand-googlescholar"
  name = "useless point counting"
  url = "https://scholar.google.com/citations?user=sd9EGi8AAAAJ"
